#!/bin/bash
#? ccli 0.1.0
#? Copyright (C) 2014 Matthew Henderson
#? License MIT
#? This is free software: you are free to change and redistribute it.
#? There is NO WARRANTY, to the extent permitted by law.

##? Usage:
##?      ccli bktdsat [options]  [--] <file>...
##?      ccli dsatur [options] [--] <file>...
##?      ccli greedy [options] [--] <file>...
##?      ccli itrgrdy [options] [--] <file>...
##?      ccli maxis [options] [--] <file>...
##?      ccli tabu [options] [--] <file>...
##?      ccli -h | --help
##?      ccli --version
##?
##? Options:
##?      --help             Show help options.
##?      --version          Print program version.
##?      --cheat            Use cheat.
##?      --kempe            Use Kempe chains.
##?      --ordering=<name>  Vertex ordering. [default: inorder]
##?      --seed=<value>     Randomisation seed value. [default: 0]
##?      --type=<name>      Algorithm type. [default: simple]

greedy=./bin/greedy.exp
dsatur=./bin/dsatur.exp

help=$(grep "^##?" "$0" | cut -c 5-)
version=$(grep "^#?"  "$0" | cut -c 4-)

eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

if ${args[--cheat]}; then
  CHEAT=1
else
  CHEAT=0
fi

if ${args[--kempe]}; then
 KEMPE="y"
else
 KEMPE="n"
fi

ORDERING_S=${args[--ordering]}
case $ORDERING_S in
 inorder) ORDERING=1 ;;
 random) ORDERING=2 ;;
 decdeg) ORDERING=3 ;;
 incdeg) ORDERING=4 ;;
 lbfsr) ORDERING=5 ;;
 lbfsd) ORDERING=6 ;;
 lbfsi) ORDERING=7 ;;
 *) ORDERING=1 ;;
esac

TYPE_S=${args[--type]}
case $TYPE_S in
 simple) TYPE=1 ;;
 large) TYPE=2 ;;
 small) TYPE=3 ;;
 random) TYPE=4 ;;
 reverse) TYPE=5 ;;
 stir) TYPE=6 ;;
 *) TYPE=1 ;;
esac

if ${args[bktdsat]} ; then
    echo "BKTDSAT Algorithm."
fi

if ${args[dsatur]} ; then
     $dsatur ${args[<file>,0]} $CHEAT $ORDERING ${args[--seed]}
fi

if ${args[greedy]} ; then
     $greedy ${args[<file>,0]} $CHEAT $KEMPE $ORDERING ${args[--seed]} $TYPE
fi

if ${args[itrgrdy]} ; then
    echo "ITRGRDY Algorithm."
fi

if ${args[maxis]} ; then
    echo "Maxis Algorithm."
fi

if ${args[tabu]} ; then
    echo "Tabu Algorithm."
fi

