#!/bin/bash
#? ccli 0.1.0
#? Copyright (C) 2014 Matthew Henderson
#? License MIT
#? This is free software: you are free to change and redistribute it.
#? There is NO WARRANTY, to the extent permitted by law.

##? Usage:
##?      ccli bktdsat [options]  [--] <file>...
##?      ccli dsatur [options] [--] <file>...
##?      ccli greedy [options] [--] <file>...
##?      ccli itrgrdy [options] [--] <file>...
##?      ccli maxis [options] [--] <file>...
##?      ccli tabu [options] [--] <file>...
##?      ccli -h | --help
##?      ccli --version
##?
##? Options:
##?      --help             Show help options.
##?      --version          Print program version.
##?      --cheat            Use cheat.
##?      --seed <value>     Randomisation seed value. [default: 0]
##?      --type <name>      Algorithm type. [default: simple]
##?      --ordering <name>  Vertex ordering. [default: inorder]
##?      --kempe            Use Kempe chains.

greedy=./bin/greedy.exp

help=$(grep "^##?" "$0" | cut -c 5-)
version=$(grep "^#?"  "$0" | cut -c 4-)

eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

if ${args[bktdsat]} ; then
    echo "BKTDSAT Algorithm."
fi

if ${args[dsatur]} ; then
    echo "DSATUR Algorithm."
fi

if ${args[greedy]} ; then
    echo ${args[--cheat]}
    echo ${args[--kempe]}
    echo ${args[--type]}
    echo ${args[--ordering]}
#    $greedy ${args[<file>,0]}
fi

if ${args[itrgrdy]} ; then
    echo "ITRGRDY Algorithm."
fi

if ${args[maxis]} ; then
    echo "Maxis Algorithm."
fi

if ${args[tabu]} ; then
    echo "Tabu Algorithm."
fi

